# Site settings
title: CI and CD with GitHub TEST
description: A demo blog
email: rudivandrunen@gmail.com
twitter_username: dvidur
github_username:  rudivandrunen
baseurl:
url: https://rudivandrunen-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
